name: Build, Push Docker Image & Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/python-docker-app:latest
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE 
          
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        

      - name: Terraform Plan
        working-directory: terraform
        run: terraform apply -auto-approve -var="image=${{ env.IMAGE }}"
        

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="image=${{ env.IMAGE }}"
        
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
